import type { Artist, Song, Beat, SubscriptionPlan } from "./schema";

// Site content. This is the single source of truth for both the client
// (which reads it directly, so the site can be deployed as static files)
// and the dev server's in-memory storage.

export const seedArtists: Artist[] = [
  {
    id: 1,
    name: "Ronnie Quest",
    role: "",
    bio: "\"For fans of experimental Hip-Hop and R&B, Ronnie Quest is the next stop of this wave, so hop on now or be sorry that you missed out later\" - Lyrical Lemonade\n\n\"He manages to switch seamlessly between the late night vibes of Toronto, the tropical rhythms of Kingston, and bounce of Los Angeles to create a myriad of sonic offerings.\"",
    imageUrl: "/IMG_2979_1750199389614.PNG",
    instagramUrl: "https://www.instagram.com/ronniequest/",
    instagramHandle: "@ronniequest",
    twitterUrl: "#",
    soundcloudUrl: "https://open.spotify.com/artist/5MhvAwI8NgndVhni9PbYOb?si=Ru_qYaO8RO-jC3rzYjILvA",
  },
  {
    id: 2,
    name: "Isaiah Bradshaw",
    role: "",
    bio: "Isaiah Bradshaw is a genre-blending artist whose smooth flows and raw lyricism are matched by a deep musicality shaped across generations. With a sound rooted in 90s and 2000s Hip-Hop and R&B, infused with the warmth of jazz and soul, Isaiah creates music that feels both nostalgic and refreshingly modern. Raised in the San Fernando Valley, his earliest influences came from the records played around the house, from his parents' hip-hop favorites to the timeless classics introduced by his grandparents. While he's also a skilled producer known for his signature sample chops, Isaiah's true foundation lies in storytelling and self-expression. Driven by a lifelong need to create, he crafts songs that resonate across eras, cultures, and emotions.",
    imageUrl: "/DSC_2113 2_1750474127673.JPG",
    instagramUrl: "https://www.instagram.com/isaiahbradshaw42/",
    instagramHandle: "@isaiahbradshaw42",
    twitterUrl: "#",
    soundcloudUrl: "https://open.spotify.com/artist/0cXN6IO8BbkBw9BBFh1YIw?si=_rr6qIifQfKorwsrKL6u9A",
  },
  {
    id: 3,
    name: "Natty Clxssic",
    role: "",
    bio: "Nathaniel Harris (aka Natty Clxssic) is a Los Angeles-based producer, composer, and keyboardist whose sound lives at the intersection of R&B, hip hop, cinematic scoring, afrobeat, and beyond. With over 20 years of musical experience—ranging from performing as a concert pianist with professional orchestras to crafting beats in the studio—Natty Clxssic brings both classical training and creative versatility to every project.\n\nHis music blends organic and synthesized textures to form rich, immersive soundscapes marked by an instinctive sense of harmony and melody. Whether he's scoring films, producing for rising artists, or composing original jingles for media platforms, Nathaniel approaches each composition with precision, emotion, and originality.",
    imageUrl: "/natty-clxssic-studio.jpg",
    instagramUrl: "https://www.instagram.com/nathanielharrismusic/",
    instagramHandle: "@nathanielharrismusic",
    twitterUrl: "#",
    soundcloudUrl: "https://open.spotify.com/artist/7pat8iIVODW5NapgHcpNva",
  },
  {
    id: 4,
    name: "Colocho",
    role: "",
    bio: "'Colocho', a Guatemalan and South Sudanese American, hailing from Silver Spring, Maryland; a cultural epicenter a street away from Washington D.C. Taking inspiration from 'alabanzas', gospel music from Latin American, Jazz & Hip Hop from D.Cs chocolate city, and African diaspora music, such as dancehall, afrobeat, and reggaeton. The visionary collides these musical virtues to build cross cultural bridges throughout the capital region of  DC, Maryland, and Virginia. Making impact for next generation through his sonics, melodies & art, he wills this vision forward by creating dialogue on issues regarding classism, colorism, & culture, with the hopes of creating consensus in our shared human experience.",
    imageUrl: "/IMG_1283_1751851934510.jpeg",
    instagramUrl: "https://www.instagram.com/_colocho/",
    instagramHandle: "@_colocho",
    twitterUrl: "#",
    soundcloudUrl: "https://open.spotify.com/artist/2VeS7YVgy4AIxQakPwe9Ff",
  },
  {
    id: 5,
    name: "NoBryant",
    role: "",
    bio: "Kobe is a multidisciplinary creative and storyteller whose work bridges culture, community, and connection. Drawing inspiration from music, film, fashion, and the spaces where people come alive, he creates with an eye for authenticity and impact. As the founder of The Third Place, Kobe documents stories that celebrate identity and belonging, blending documentary, party culture, and human narrative into vibrant, cinematic experiences. With a passion for capturing what makes people and places unique, he brings a thoughtful, collaborative energy to every project he's part of.",
    imageUrl: "/IMG_7359_2_1752639999752.JPG",
    instagramUrl: "https://www.instagram.com/nobryant/?hl=en",
    instagramHandle: "@nobryant",
    twitterUrl: "#",
    soundcloudUrl: "#",
  },
];

export const seedSongs: Song[] = [
  {
    id: 1,
    title: "Coffee In The Hills",
    artistId: 1,
    duration: "3:42",
    spotifyUrl: "https://open.spotify.com/track/5Q8djOrD4GZH0krZSHcKaJ?si=N9ZKv6pwRBmDkpk4y0qkiw",
    artworkUrl: "https://images.unsplash.com/photo-1459749411175-04bf5292ceea?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400",
    youtubeUrl: "https://youtu.be/eUr5pWT3LPU",
  },
  {
    id: 2,
    title: "Ronnie On The Weekend/Who's Fault",
    artistId: 1,
    duration: "3:45",
    spotifyUrl: null,
    artworkUrl: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400",
    youtubeUrl: "https://www.youtube.com/watch?v=w65xitpKUjk",
  },
  {
    id: 3,
    title: "Heavy Handed",
    artistId: 2,
    duration: "3:15",
    spotifyUrl: "https://open.spotify.com/artist/0cXN6IO8BbkBw9BBFh1YIw",
    artworkUrl: "https://images.unsplash.com/photo-1516280440614-37939bbacd81?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=400&h=400",
    youtubeUrl: "https://www.youtube.com/watch?v=C5vvv80Rn-k",
  },
  {
    id: 4,
    title: "Cut Loose",
    artistId: 2,
    duration: "4:12",
    spotifyUrl: "https://open.spotify.com/artist/0cXN6IO8BbkBw9BBFh1YIw",
    artworkUrl: "https://img.youtube.com/vi/la4AV88zpLw/maxresdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=la4AV88zpLw&list=RDla4AV88zpLw&start_radio=1&ab_channel=IsaiahBradshaw",
  },
  {
    id: 5,
    title: "Natty Clxssic Spotify Playlist",
    artistId: 3,
    duration: "Playlist",
    spotifyUrl: "https://open.spotify.com/playlist/3YQJ5n0WWufygNc2zq8It6?si=XDDK8VZAQMikc6h9FCc_-w&pi=P4lO5AenRXqr_",
    artworkUrl: "/natty-playlist-rotated.jpg",
    youtubeUrl: null,
  },
  {
    id: 6,
    title: "Chemphe",
    artistId: 4,
    duration: "3:20",
    spotifyUrl: "https://open.spotify.com/artist/2VeS7YVgy4AIxQakPwe9Ff",
    artworkUrl: "https://img.youtube.com/vi/cql-b95kvpk/maxresdefault.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=cql-b95kvpk&list=RDcql-b95kvpk&start_radio=1&ab_channel=Colocho",
  },
];

export const seedBeats: Beat[] = [
  {
    id: 1,
    title: "Trap Nation",
    producerId: 1,
    bpm: 140,
    key: "C Minor",
    previewUrl: "/audio/trap-nation-preview.mp3",
    price: "29.99",
    isExclusive: false,
  },
  {
    id: 2,
    title: "R&B Soul",
    producerId: 2,
    bpm: 85,
    key: "D Major",
    previewUrl: "/audio/rnb-soul-preview.mp3",
    price: "34.99",
    isExclusive: false,
  },
  {
    id: 3,
    title: "Hip Hop Bangers",
    producerId: 3,
    bpm: 120,
    key: "G Minor",
    previewUrl: "/audio/hiphop-bangers-preview.mp3",
    price: "39.99",
    isExclusive: true,
  },
  {
    id: 4,
    title: "Chill Vibes",
    producerId: 1,
    bpm: 95,
    key: "A Minor",
    previewUrl: "/audio/chill-vibes-preview.mp3",
    price: "24.99",
    isExclusive: false,
  },
];

export const seedSubscriptionPlans: SubscriptionPlan[] = [
  {
    id: 1,
    name: "Basic",
    price: "5.69",
    description: "Perfect for getting started",
    features: ["10 beat downloads/month", "Standard quality (MP3)", "Basic license included"],
    isPopular: false,
  },
  {
    id: 2,
    name: "Pro",
    price: "19.99",
    description: "For serious creators",
    features: ["50 beat downloads/month", "High quality (WAV + MP3)", "Premium license included", "Stems available"],
    isPopular: true,
  },
  {
    id: 3,
    name: "Premium",
    price: "39.99",
    description: "Unlimited access",
    features: ["Unlimited downloads", "All formats (WAV, MP3, MIDI)", "Exclusive beats", "Custom requests"],
    isPopular: false,
  },
];
